export type Founder = {
  id: number;
  name: string;
  org: string;
  bio: string;
  image?: string;
  website?: string;
};

const firstTen: Founder[] = [
  {
    id: 1,
    name: "Zoe Terry",
    org: "",
    bio: "Founder and CEO - Zoe's Dolls",
    image: "/images/triibe100/Zoe Terry.png",
    website: "https://zoesdolls.com/",
  },
  {
    id: 2,
    name: "Varuni Chopra",
    org: "",
    bio: "Founder - Bridge The Gap",
    image: "/images/triibe100/VaruniChopra.png",
    website: "https://bridgethegapinitiative.org/",
  },
  {
    id: 3,
    name: "Trisha Prabhu",
    org: "",
    bio: "Founder and CEO - ReThink Citizens",
    image: "/images/triibe100/Trisha Prabhu.png",
    website: "https://rethinkcitizens.org/",
  },
  {
    id: 4,
    name: "Shrusti Amula",
    org: "",
    bio: "Founder - Rise N Shine Foundation",
    image: "/images/triibe100/Shrusti Amula.png",
    website: "https://www.risenshinefoundation.org/",
  },
  {
    id: 5,
    name: "Sharona Shnayder",
    org: "",
    bio: "Founder - Tuesdays for Trash",
    image: "/images/triibe100/Sharona Shnayder.png",
    website: "https://tuesdaysfortrash.com/",
  },
  {
    id: 6,
    name: "Sayed Zubaer Hasan",
    org: "",
    bio: "Founder and CEO - Krishi Shwapno",
    image: "/images/triibe100/Sayed-Zubaer-Hasan 2.png",
    website: "https://krishishwapno.com/",
  },
  {
    id: 7,
    name: "Samin Bhan",
    org: "",
    bio: "Founder - Lookupp",
    image: "/images/triibe100/SaminBhan.jpg",
    website: "https://www.lookupp.net/",
  },
  {
    id: 8,
    name: "Rimza Razaque",
    org: "",
    bio: "Founder - Al Arzen",
    image: "/images/triibe100/Rimza Razaque.png",
    website: "https://www.linkedin.com/company/al-arzen/",
  },
  {
    id: 9,
    name: "Rachel Parent",
    org: "",
    bio: "Founder - Kids Right to Know",
    image: "/images/triibe100/Rachel Parent.png",
    website: "https://www.kidsrighttoknow.com/",
  },
  {
    id: 10,
    name: "Olivia Zhang",
    org: "",
    bio: "Founder - Cancer Kids First",
    image: "/images/triibe100/Olivia Zhang.png",
    website: "https://www.cancerkidsfirst.org/",
  },
];

const restOverrides: Partial<Founder>[] = [
  {
    name: "Nils Rauscher",
    org: "",
    bio: "Co-Founder - Zukunftsforum Baden-Baden",
    image: "/images/triibe100/Nils Rauscher.png",
    website: "https://zkfbb.de/",
  },
  {
    name: "Nayla Jimenez",
    org: "",
    bio: "Executive Director - Philippine Health Initiative",
    image: "/images/triibe100/NaylaJimenez.jpg",
    website: "https://www.philippinehealthinitiative.org/",
  },
  {
    name: "Mirus Ponon",
    org: "",
    bio: "Founder - ASEAN Youth Advocates Network",
    image: "/images/triibe100/Mirus Ponon.png",
    website:
      "https://wps.asean.org/organization/asean-youth-advocates-network/",
  },
  {
    name: "Mathias Charles Yabe",
    org: "",
    bio: "CEO - AkoFresh",
    image: "/images/triibe100/Mathias Charles Yabe.png",
    website: "https://www.akofresh.com/",
  },
  {
    name: "Maria Keller",
    org: "",
    bio: "Founder - Read Indeed",
    image: "/images/triibe100/Maria Keller.png",
    website: "https://www.linkedin.com/company/readindeed/",
  },
  {
    name: "Josh Fields",
    org: "",
    bio: "Executive Director - The Next Step Programs",
    image: "/images/triibe100/Josh Fields.png",
    website: "https://tnsprograms.org/",
  },
  {
    name: "Jared Fenton",
    org: "",
    bio: "Founder - The Reflect Organization",
    image: "/images/triibe100/Jared Fenton.png",
    website: "https://www.reflecteffect.org/",
  },
  {
    name: "Jahnavi Rao",
    org: "",
    bio: "President and Founder - New Voters",
    image: "/images/triibe100/Jahnavi Rao.png",
    website: "https://www.new-voters.org/",
  },
  {
    name: "Stanley Anigbogu",
    org: "",
    bio: "Founder - LightED Impact Foundation",
    image: "/images/triibe100/Stanley Anigbogu.png",
    website: "https://lightedimpact.org/",
  },
  {
    name: "Hikaru (Wakeel) Hayakawa",
    org: "",
    bio: "Executive Director - Climate Cardinals",
    image: "/images/triibe100/Hikaru Wakeel Hayakawa.png",
    website: "https://www.climatecardinals.org/",
  },
  {
    name: "Hayfa Sdiri",
    org: "",
    bio: "Co-Founder and CIO - RIVET | BBC 100 2019",
    image: "/images/triibe100/Hayfa Sdiri.png",
    website: "https://www.rivet.org/",
  },
  {
    name: "Grace Liu",
    org: "",
    bio: "Founder - Research To Empower",
    image: "/images/triibe100/Grace Liu.png",
    website: "https://www.research2empower.org/",
  },
  {
    name: "Gitanjali Rao",
    org: "",
    bio: "Global Keynote - Vervient Foundation",
    image: "/images/triibe100/Gitanjali Rao.png",
    website: "https://vervient.org/",
  },
  {
    name: "Esha Venkat",
    org: "",
    bio: "COO, Speaker and Founder - NEST4US",
    image: "/images/triibe100/Esha Venkat.png",
    website: "https://nest4us.org/",
  },
  {
    name: "Dr. Khadija Serwaah Owusu",
    org: "",
    bio: "Founder - AKAYA",
    image: "/images/triibe100/Dr. Khadija Serwaah Owusu.png",
    website: "https://www.akayafoundation.com/",
  },
  {
    name: "Diana Chao",
    org: "",
    bio: "Founder - Letters to Strangers",
    image: "/images/triibe100/Diana Chao.png",
    website: "https://www.letterstostrangers.org/",
  },
  {
    name: "Cole Mattox",
    org: "",
    bio: "Co-Founder and Co-Chairman - First Generation Investors",
    image: "/images/triibe100/Cole Mattox.png",
    website: "https://www.firstgenerationinvestors.com/",
  },
  {
    name: "Claire Chi",
    org: "",
    bio: "Founder and Executive Director - Dancing Against Hunger",
    image: "/images/triibe100/Claire Chi.png",
    website: "https://www.dancingagainsthunger.org/",
  },
  {
    name: "Chethan Gowda",
    org: "",
    bio: "Founder - Khoon",
    image: "/images/triibe100/Chethan M.png",
    website: "https://www.khoon.org/",
  },
  {
    name: "Ben Erler",
    org: "",
    bio: "Former Chairman and Board Member for Education - Young Founders Network",
    image: "/images/triibe100/Ben Erler.png",
    website: "https://youngfounders.network/",
  },
  {
    name: "Anna Luísa Beserra",
    org: "",
    bio: "CEO - Sustainable Development & Water For All",
    image: "/images/triibe100/Anna Luísa Beserra.png",
    website: "https://www.sdwforall.com/en",
  },
  {
    name: "Alexia Hilbertidou",
    org: "",
    bio: "Founder & CEO - GirlBoss New Zealand",
    image: "/images/triibe100/AlexiaHilbertidou.jpg",
    website: "https://www.girlboss.nz/",
  },
  {
    name: "Neha Shukla",
    org: "",
    bio: "Founder & Executive Director, Innovation for Everyone",
    image: "/images/triibe100/NehaShukla.jpg",
    website: "https://www.innoforeveryone.org/",
  },
  {
    name: "Natalie Meyer",
    org: "",
    bio: "Founder & Managing Director, Arc Health",
    image: "/images/triibe100/NatalieMeyer.jpg",
    website: "https://arc-health.org/",
  },
  {
    name: "Bella Brown",
    org: "",
    bio: "Co-Founder, Living Outside",
    image: "/images/triibe100/BellaBrown.jpg",
    website: "https://www.livingoutside.org/",
  },
  {
    name: "Nav Agarwal",
    org: "",
    bio: "Founder, One Step Greener",
    image: "/images/triibe100/NavAgarwal.jpg",
    website: "https://www.onestepgreener.org/",
  },
  {
    name: "Olivier UWISHEMA",
    org: "",
    bio: "Founder and Chairman, Oli Health Magazine Organization",
    image: "/images/triibe100/OlivierUWISHEMA.jpg",
    website: "https://www.olihealthmagazine.org/",
  },
  {
    name: "Kelsey Cadien",
    org: "",
    bio: "Co-Founder, Kelsey & Cambel's Kids Care",
    image: "/images/triibe100/KelseyCadien.jpg",
    website: "https://www.kckidscare.org/",
  },
  {
    name: "Emily Cho",
    org: "",
    bio: "Founder & Executive Director, Juvie for STEM",
    image: "/images/triibe100/EmilyCho.jpg",
    website: "https://www.juvieforstem.org/",
  },
  {
    name: "Mary Zhu",
    org: "",
    bio: "Founder & Executive Director, Develop for Good",
    image: "/images/triibe100/MaryZhu.jpg",
    website: "https://www.developforgood.org/",
  },
  {
    name: "Owen Tanner-Flomberg",
    org: "",
    bio: "Founding Executive Director, Student Basic Needs Coalition",
    image: "/images/triibe100/OwenTanner-Flomberg.png",
    website: "https://studentbasicneeds.com/",
  },
  {
    name: "Adaobi Okeke",
    org: "",
    bio: "Co-Founder, CIF Initiative",
    image: "/images/triibe100/AdaobiOkeke.jpg",
    website: "https://www.linkedin.com/company/cif-initiative/",
  },
  {
    name: "Val Amiel Vestil",
    org: "",
    bio: "Executive Director, Association of Young Environmental Journalists",
    image: "/images/triibe100/ValAmielVestil.jpg",
    website: "https://www.linkedin.com/company/association-of-young-environmental-journalists/",
  },
  {
    name: "Ava Langridge",
    org: "",
    bio: "Founder & Executive Director, Our Youth 4 The Climate",
    image: "/images/triibe100/AvaLangridge.jpg",
    website: "https://oy4c.org/",
  },
  {
    name: "Kehkashan Basu",
    org: "",
    bio: "Sustainability Expert, Green Hope Foundation",
    image: "/images/triibe100/KehkashanBasu.jpeg",
    website: "https://www.thegreenhopefoundation.org/",
  },
  {
    name: "Rijve Arefin",
    org: "",
    bio: "Co-Founder, Awareness 360",
    image: "/images/triibe100/RijveArefin.jpg",
    website: "https://awareness360.org.my/",
  },
  {
    name: "Joseph Nguthiru",
    org: "",
    bio: "Co-Founder & Engineer, AfroClimate",
    image: "/images/triibe100/JosephNguthiru.jpg",
    website: "https://www.afroclimate.org/",
  },
  {
    name: "Khloe Thompson",
    org: "",
    bio: "Founder, Khloe Kares",
    image: "/images/triibe100/KhloeThompson.jpg",
    website: "https://www.khloekares.com/#/",
  },
  {
    name: "Marie-Claire Graf",
    org: "",
    bio: "Co-Founder, Youth Negotiators Academy",
    image: "/images/triibe100/Marie-ClaireGraf.jpg",
    website: "https://www.youthnegotiators.org/",
  },
  {
    name: "Jerome Foster II",
    org: "",
    bio: "Founder & Executive Director, WaicUp",
    image: "/images/triibe100/JeromeFosterII.jpg",
    website: "https://www.waicup.org/",
  },
  {
    name: "Sonali Ratnasinghe",
    org: "",
    bio: "Founder & Executive Director, Youth Ambassadors of Service",
    image: "/images/triibe100/SonaliRatnasinghe.jpg",
    website: "https://www.youthambassadorsofservice.org/",
  },
  {
    name: "Ben Mayele Jeme",
    org: "",
    bio: "Founder & Executive Director, Nakujali Foundation",
    image: "/images/triibe100/BenMayeleJeme.jpg",
    website: "https://www.nakujalifoundation.org/",
  },
  {
    name: "Caeley Looney",
    org: "",
    bio: "Founder & CEO, Reinvented Magazine",
    image: "/images/triibe100/CaeleyLooney.jpg",
    website: "https://www.reinventedmagazine.com/",
  },
  {
    name: "Shreyaa Venkat",
    org: "",
    bio: "Founder & CEO, NEST4US",
    image: "/images/triibe100/ShreyaaVenkat.jpg",
    website: "https://nest4us.org/",
  },
  {
    name: "Anne-Sophie Frédérick",
    org: "",
    bio: "Founder & Product Lead, Haitech Learning",
    image: "/images/triibe100/Anne-SophieFrederick.jpg",
    website: "https://www.haitechlearning.org/",
  },
  {
    name: "Derin Ege Sezgin",
    org: "",
    bio: "Founder & President, SDG Youth Connect",
    image: "/images/triibe100/DerinEgeSezgin.png",
    website: "https://www.sdgyouthconnect.org/",
  },
  {
    name: "Alex Edgar",
    org: "",
    bio: "Co-Founder, Youth 250",
    image: "/images/triibe100/AlexEdgar.jpg",
    website: "https://historymadebyus.org/youth250",
  },
  {
    name: "Maya Gowda",
    org: "",
    bio: "Founder & President, Students for Environmental Education & Discovery",
    image: "/images/triibe100/MayaGowda.jpg",
    website: "https://www.seedclimatechange.org/",
  },
  {
    name: "Arjun Sharda",
    org: "",
    bio: "Executive Director, TLEEM",
    image: "/images/triibe100/ArjunSharda.jpg",
    website: "https://tleem.org/",
  },
  {
    name: "Madison Quesnel",
    org: "",
    bio: "Founder & Executive Director, Building Grace",
    image: "/images/triibe100/Madison Quesnel.jpeg",
    website: "https://www.buildinggracehelpingwomen.com/",
  },
  {
    name: "Felix Atamba",
    org: "",
    bio: "Founder & Youth Project Lead, Youth Against Hunger Initiative",
    image: "/images/triibe100/FelixAtamba.jpg",
    website: "https://www.linkedin.com/company/youthagainsthunger/",
  },
  {
    name: "Ethan Hill",
    org: "",
    bio: "Founder, Ethan's Heart Bags4Blessings",
    image: "/images/triibe100/EthanHill.jpeg",
    website: "http://www.ethansheartbham.org/",
  },
  {
    name: "Crystal Yang",
    org: "",
    bio: "Founder & CEO, Audemy",
    image: "/images/summit/CrystalYang.png",
    website: "https://audemy.org/",
  },
  {
    name: "Marina El Khawand",
    org: "",
    bio: "Founder & President, Medonations",
    image: "/images/triibe100/MarinaElKhawand.jpg",
    website: "https://medonations.org/",
  },
  {
    name: "Zoya Kalinsky",
    org: "",
    bio: "Founder & Executive Director, UnitEd Youth Council",
    image: "/images/triibe100/ZoyaKalinsky.jpeg",
    website: "https://www.unitedyc.org/",
  },
  {
    name: "Ebun Lawal",
    org: "",
    bio: "Founder & Managing Director, Corporate Jungle Impact",
    image: "/images/triibe100/EbunLawal.jpg",
    website: "https://uk.linkedin.com/company/corporate-jungle-impact",
  },

  {
    name: "COMING_SOON_PLACEHOLDER",
    org: "",
    bio: "",
  },
];

const rest: Founder[] = restOverrides.map((override, i) => ({
  id: i + 11,
  name: "Name",
  org: "Non Profit",
  bio: "Coming soon.",
  website: "",
  ...override,
}));

export const founders: Founder[] = [...firstTen, ...rest];
